/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-10 05:36:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.lesson;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lesson_005fpop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635990606003L));
    _jspx_dependants.put("jar:file:/C:/springproject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMyBatisExam/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>과목 테이블 팝업</title>\n");
      out.write("	<style type=\"text/css\">\n");
      out.write("		.required{color:red;}\n");
      out.write("		table{width:450px;}\n");
      out.write("		table th{width:120px; text-align:left;}\n");
      out.write("		input[type=\"text\"]{width:330px;}\n");
      out.write("	</style>\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("		$(document).ready(function(){\n");
      out.write("			var mode = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("			if(mode == \"insert\"){\n");
      out.write("				$('#insertData').attr('disabled',false);\n");
      out.write("				$('#updateData').attr('disabled',true);\n");
      out.write("				$('#deleteData').attr('disabled',true);\n");
      out.write("			}else if(mode == \"update\"){\n");
      out.write("				$('#insertData').attr('disabled',true);\n");
      out.write("				$('#updateData').attr('disabled',false);\n");
      out.write("				$('#deleteData').attr('disabled',false);\n");
      out.write("				\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			$(\"#insertData\").click(function(){\n");
      out.write("				if(!validateForm()) return;\n");
      out.write("				if($(\"#no\").val()==\"\") $(\"#no\").val(0);\n");
      out.write("				if(confirm('등록을 진행할까요?')){\n");
      out.write("					$(\"#lessonForm\").attr(\"action\",\"/lesson/insertLesson.do\");\n");
      out.write("					$(\"#lessonForm\").submit();\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("				\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("			$(\"#updateData\").click(function(){\n");
      out.write("				if(!validateForm()) return;\n");
      out.write("				if(confirm('수정을 진행할까요?')){\n");
      out.write("					$(\"#lessonForm\").attr(\"action\",\"/lesson/updateLesson.do\");\n");
      out.write("					$(\"#lessonForm\").submit();\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("				\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("			$(\"#deleteData\").click(function(){\n");
      out.write("				if(confirm('삭제를 진행할까요?')){\n");
      out.write("					$(\"#lessonForm\").attr(\"action\",\"/lesson/deleteLesson.do\");\n");
      out.write("					$(\"#lessonForm\").submit();\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("				\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("			$(\"#closeWindow\").click(function(){\n");
      out.write("				window.close();\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		function validateForm(){\n");
      out.write("			if($(\"#lnum\").val().replace(/\\s/g,\"\")==\"\"){\n");
      out.write("				alert('과목 코드를 입력해주세요.');\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			if($(\"#lname\").val().replace(/\\s/g,\"\")==\"\"){\n");
      out.write("				alert('과목명을 입력해주세요.');\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("			return true;\n");
      out.write("			\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<p></p>\n");
      out.write("	<div>\n");
      out.write("			<form id=\"lessonForm\" name=\"lessonForm\" method=\"post\">\n");
      out.write("				<input type=\"hidden\" id=\"no\" name=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lessonVO.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("				<table border=\"1\">\n");
      out.write("					<thead>\n");
      out.write("						<tr>\n");
      out.write("							<td colspan=\"2\" align=\"center\">\n");
      out.write("								<h4>과목 테이블 팝업창 [Spring] </h4></td>\n");
      out.write("						</tr>\n");
      out.write("					</thead>\n");
      out.write("				<tbody>\n");
      out.write("				<tr>\n");
      out.write("					<th><span class=\"required\">*</span>과목코드</th>\n");
      out.write("					<td><input type=\"text\" id=\"lnum\"\n");
      out.write("						name=\"lnum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lessonVO.lnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<th><span class=\"required\">*</span>과목명</th>\n");
      out.write("					<td><input type=\"text\" id=\"lname\"\n");
      out.write("						name=\"lname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lessonVO.lname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\n");
      out.write("				</tr>\n");
      out.write("				</tbody>\n");
      out.write("			</table>\n");
      out.write("		</form>\n");
      out.write("	\n");
      out.write("	</div>\n");
      out.write("	<div>\n");
      out.write("	<p></p>\n");
      out.write("		<table border=\"0\">\n");
      out.write("			<tr align=\"center\">\n");
      out.write("				<td>\n");
      out.write("					<input type=\"button\" id=\"insertData\" value=\"등록\" /></td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"button\" id=\"updateData\" value=\"수정\" /></td>\n");
      out.write("				<td>\n");
      out.write("					<input type=\"button\" id=\"deleteData\" value=\"삭제\" /></td>\n");
      out.write("					\n");
      out.write("				<td>\n");
      out.write("					<input type=\"button\" id=\"closeWindow\" value=\"닫기\" /></td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
